### PR TITLE
Fixed naming according to purescript-css

### PR DESCRIPTION
**Pull request by eskimor**
Css became CSS.

I was not able to fully test those minimal changes as purescript-css
won't compile for me unfortunately.

### CODE REVIEW

**Comment by cryogenian** [comment]
Build fails because `purescript-css` omit `qualified` in imports. And this can be done only with purescript `>0.7.5`. I think altering purescript version in `package.json` will help.

**Comment by garyb** [comment]
Sounds about right, @eskimor can you bump it to `^0.7.6` please?

**Comment by eskimor** [comment]
Done :-)

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
