### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pbrant**

### CODE REVIEW

**Comment by pbrant** [comment]
It looks like the Travis build is using an older compiler version. The dependency updates should work with 0.12.2+.

**Comment by garyb** [comment]
Hmm yeah, for some reason the compiler version is fixed to 0.12.0 in the `package.json`, could you change that to `^0.12.3` too?

**Comment by pbrant** [comment]
This is done (along with pulp and psa).

**Comment by garyb** [comment]
Um, not sure what happened here. Sorry!

**Pull request closed without merging**
