### PR TITLE
Purescript 0.9 update

### PR DESCRIPTION
**Pull request by berdario**
Apparently this also requires a new release of purescript-css (I haven't bumped its version in bower.json)

### CODE REVIEW

**Comment by jdegoes** [comment]
@berdario There's a new release of `purescript-css` out!

**Comment by berdario** [comment]
Awesome, now travis builds successfully as well

**Comment by jdegoes** [comment]
Thanks! Is there a need to bump up `purescript-psa` or other bower / npm dependencies?

**Comment by berdario** [comment]
Not sure

## Not that I'm aware of... But I'm extremely new to Purescript

Sent from mobile. Please excuse my brevity.

**Comment by garyb** [comment]
`purescript-psa` is fine at this version :+1:

**Pull request merged**
